# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16EwHQtCBowtsK-xroMCZVolAICDlO_ET
"""

import pandas as pd
import matplotlib.pyplot as plt

def analyze_data(df):

    summary_numeric = df.describe()
    print("\nSummary Statistics for Numeric Columns:")
    print(summary_numeric)
    print("\nSummary Statistics for Categorical Columns:")
    summary_categorical = df.describe(include=['object'])
    print(summary_categorical)
    numeric_column = df.select_dtypes(include=['float64', 'int64']).columns[0]
    plt.figure(figsize=(8, 6))
    plt.hist(df[numeric_column], bins=20, edgecolor='k')
    plt.xlabel(numeric_column)
    plt.ylabel('Frequency')
    plt.title(f'Histogram of {numeric_column}')
    plt.show()

def process_data(csv_file):
    try:

        df = pd.read_csv(csv_file)
        print("\nOriginal Data:")
        print(df)
        analyze_data(df)
        processed_csv_file = "processed_data.csv"
        df.to_csv(processed_csv_file, index=False)
        print(f"\nProcessed data saved to '{processed_csv_file}'.")

        return df
    except FileNotFoundError:
        print(f"File '{csv_file}' not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    csv_file_path = "filepath/filename.csv" #replace it with your file dir
    process_data(csv_file_path)