# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KyJY3ppOZV5ey51ZUeWbNe9tER9YhFes
"""

import random
import string
import time

def generate_password(length=12):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

while True:
    password = generate_password()
    print("Generated Password:", password)
    time.sleep(0.5)